"""Add page number to document chunks

Revision ID: 6f16c8898d3c
Revises: 34c2170fe182
Create Date: 2026-07-22 22:18:01.509384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f16c8898d3c'
down_revision: Union[str, Sequence[str], None] = '34c2170fe182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
